# Generated by Django 5.0.1 on 2024-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_product_delete_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://public.bnbstatic.com/image/cms/blog/20230605/026722ab-19ca-4c7a-ae61-a98af8851159.png', upload_to='image_path/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE'), ('Not Available', 'NOT AVAILABLE')], max_length=50),
        ),
    ]
